"""
Config package - exports configuration variables
"""
from .config import (
    DB_CONFIG,
    PINECONE_API_KEY,
    PINECONE_ENVIRONMENT,
    PINECONE_INDEX_NAME,
    PINECONE_DIMENSION,
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    ARTICLES_DIR,
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    MAX_CONCURRENT_REQUESTS,
    REQUEST_TIMEOUT,
    RATE_LIMIT_DELAY,
    MAX_RETRIES,
    MIN_ARTICLE_LENGTH,
    RSS_FEEDS
)

__all__ = [
    'DB_CONFIG',
    'PINECONE_API_KEY',
    'PINECONE_ENVIRONMENT',
    'PINECONE_INDEX_NAME',
    'PINECONE_DIMENSION',
    'OLLAMA_BASE_URL',
    'OLLAMA_MODEL',
    'ARTICLES_DIR',
    'CHUNK_SIZE',
    'CHUNK_OVERLAP',
    'MAX_CONCURRENT_REQUESTS',
    'REQUEST_TIMEOUT',
    'RATE_LIMIT_DELAY',
    'MAX_RETRIES',
    'MIN_ARTICLE_LENGTH',
    'RSS_FEEDS'
]

